//C++ Abstract Syntax Implementation generated by the BNF Converter.
#include <algorithm>
#include <string>
#include <iostream>
#include <vector>
#include "Absyn.H"

/********************   SNum    ********************/
SNum::SNum(Integer p1)
{
  integer_ = p1;

}

SNum::SNum(const SNum & other)
{
  integer_ = other.integer_;

}

SNum &SNum::operator=(const SNum & other)
{
  SNum tmp(other);
  swap(tmp);
  return *this;
}

void SNum::swap(SNum & other)
{
  std::swap(integer_, other.integer_);

}

SNum::~SNum()
{

}

void SNum::accept(Visitor *v)
{
  v->visitSNum(this);
}

SNum *SNum::clone() const
{
  return new SNum(*this);
}



/********************   SString    ********************/
SString::SString(String p1)
{
  string_ = p1;

}

SString::SString(const SString & other)
{
  string_ = other.string_;

}

SString &SString::operator=(const SString & other)
{
  SString tmp(other);
  swap(tmp);
  return *this;
}

void SString::swap(SString & other)
{
  std::swap(string_, other.string_);

}

SString::~SString()
{

}

void SString::accept(Visitor *v)
{
  v->visitSString(this);
}

SString *SString::clone() const
{
  return new SString(*this);
}



/********************   SAtom    ********************/
SAtom::SAtom(Ident p1)
{
  ident_ = p1;

}

SAtom::SAtom(const SAtom & other)
{
  ident_ = other.ident_;

}

SAtom &SAtom::operator=(const SAtom & other)
{
  SAtom tmp(other);
  swap(tmp);
  return *this;
}

void SAtom::swap(SAtom & other)
{
  std::swap(ident_, other.ident_);

}

SAtom::~SAtom()
{

}

void SAtom::accept(Visitor *v)
{
  v->visitSAtom(this);
}

SAtom *SAtom::clone() const
{
  return new SAtom(*this);
}



/********************   SCons    ********************/
SCons::SCons(ListSExpr *p1)
{
  listsexpr_ = p1;

}

SCons::SCons(const SCons & other)
{
  listsexpr_ = other.listsexpr_->clone();

}

SCons &SCons::operator=(const SCons & other)
{
  SCons tmp(other);
  swap(tmp);
  return *this;
}

void SCons::swap(SCons & other)
{
  std::swap(listsexpr_, other.listsexpr_);

}

SCons::~SCons()
{
  delete(listsexpr_);

}

void SCons::accept(Visitor *v)
{
  v->visitSCons(this);
}

SCons *SCons::clone() const
{
  return new SCons(*this);
}




/********************   ListSExpr    ********************/

void ListSExpr::accept(Visitor *v)
{
  v->visitListSExpr(this);
}


ListSExpr *ListSExpr::clone() const
{
  return new ListSExpr(*this);
}




